services:
  postgre:
    image: postgres:13.16
    restart: always
    env_file:
      - .homolog.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - postgre_data:/var/lib/postgresql/data

  ecommerce:
    image: fabricioveronez/fake-shop
    restart: always
    env_file:
      - .homolog.env
    environment:
      DB_HOST: postgre
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
      FLASK_APP: index.py
    ports:
      - 5000:5000
    depends_on:
      - postgre

volumes:
  postgre_data:
